### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by alex85120** [alex85120/Alex-The-Bot#1]
This is just a personal to-do list that I keep track of. Anyone is welcome to contribute if they want.

- [ ] The code is very, VERY messy. Separate the commands into functions, or even rewrite the code entirely.
- [ ] Add some new image commands (maybe one that posts the most used color and least used color, one that takes the average of all colors in the picture, and some more filters)
- [ ] Add some voice chat functionality (so far the only things the bot can do are joining and leaving. Maybe have it able to play YouTube links or local files.)

The following things are optional things to add to the bot but would be nice to have:

- [ ] Add a currency
- [ ] Add some actual utilities 😛 

Either list may be updated as I find new stuff that's missing.
